[package]
name = "cobble"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]
edition = "2018"

[dependencies]
ozelot = "0.8"
structopt = "0.2"
rpassword = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
